main.yml: # The playbook name

  # The path to the playbook, relative to $AOH_PLAYBOOKS_DIR. Defaults to the
  # playbook name.
  path: playbooks/playbook.yml

  # The path to an associated Ansible config file, if one exists.
  config: playbooks/ansible.cfg

  # The hostname to assign to clients. If omitted or null, each client is
  # assigned the hostname that it reports for itself.
  host: my-aoh-host

  # The groups to assign to clients, in addition to the aoh group and any groups
  # defined in inventory files.
  groups:
    - group1
    - group2

  # Whether to require a password to execute the playbook. Passwords must be
  # specified separately in the $AOH_PASSWORDS_FILE file (see below). Defaults
  # to false.
  password: true

  # Whether to print Ansible output on the client. Defaults to true.
  output: true

  # The ansible-playbooks options that users are allowed to invoke. Short and
  # long option forms must be specified separately. A reasonable set of safe
  # options are allowed by default, see aoh/security.py.
  allow_opts:
    - '--become-method'

  # A list of ansible-playbook options that users are not allowed to invoke.
  # This overrides the default allowed options and the options specified in
  # allow_opts. Some options are always blocked, see aoh/security.py.
  block_opts:
    - '--list-tags'

  # Whether to allow clients to use Jinja expressions in ansible-playbook
  # arguments. Defaults to false.
  jinja_args: true

  # Additional raw ansible-playbook options
  extra_args:
    - '--diff'

  # The description displayed on the playbook web page. Defaults to null, which
  # disables the playbook web page.
  web_description: 'Run the main.yml playbook with a single command:'
